Fix check if args to script are invalid
intel-ai/icl pull request #77
Opened 2024-03-21 12:02 UTC by arunjose696

Checks is arguments to aws.sh is invalid, this can save confusion using the script. 
eg
Running ./aws.sh --destroy instead of delete would  just relaunch cluster causing confusion, this can be prevented by validating args.

2024-03-21 16:00 UTC, pbchekin requested changes
Several suggestions. The biggest question is how this use case is supposed to work?
```
./aws.sh --console kubectl get nodes
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/functions.sh
> +  if [ "$invalid_arg" = true ]; then
Nit: use double brackets for consistency with the rest of the file, double equal sign, also with bash you do not need to enclose the variable in double quotes in double brackets:
```suggestion
  if [[ $invalid_arg == true ]]; then
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/functions.sh
> +function check_args(){
```suggestion
function check_args() {
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/aws.sh
> +check_args $@ allowed
`allowed` is a global variable, no need to pass. Also passing like this does not work, recommended change:
```suggestion
check_args "$@"
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/functions.sh
> +  allowed=$2
`$2` is the second argument, which is not `allowed`, i recommend to use the global one
```suggestion
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/functions.sh
> +  for arg in "$1"; do
```suggestion
  for arg in "$@"; do
```

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/gke.sh
> +allowed=("--help" "--console" "--check" "--render" "--deploy-gke" "--deploy-x1" "--config" "--delete" "--delete-x1" "--delete-gke" "--gcloud-login" "" "--start-proxy" "--stop-proxy")
Do you need `""` in the list?

2024-03-21 16:00 UTC, pbchekin commented on scripts/deploy/gke.sh
> +check_args $@ allowed
```suggestion
check_args "$@"
```

2024-03-22 07:06 UTC, arunjose696 commented
> Several suggestions. The biggest question is how this use case is supposed to work?
> 
> ```
> ./aws.sh --console kubectl get nodes
> ```

Have addressed this case now, the 

> Several suggestions. The biggest question is how this use case is supposed to work?
> 
> ```
> ./aws.sh --console kubectl get nodes
> ```

have addressed this now the loop in check_args would break if it sees console, so If console is encountered it does not check if remaining args are invalid.

2024-03-22 07:06 UTC, arunjose696 commented on scripts/deploy/gke.sh
> +allowed=("--help" "--console" "--check" "--render" "--deploy-gke" "--deploy-x1" "--config" "--delete" "--delete-x1" "--delete-gke" "--gcloud-login" "" "--start-proxy" "--stop-proxy")
Removed them

2024-03-22 14:42 UTC, pbchekin commented on scripts/deploy/functions.sh
> +      if [ $arg = "--console" ]; then
```suggestion
      if [[ $arg == "--console" ]]; then
```

2024-03-22 15:51 UTC, pbchekin approved these changes

2024-03-28 19:03 UTC, pbchekin commented
Merged to a new repository: https://github.com/aregm/icl/commit/ab87d531b1f2507c4533256a748096e5148b5701

2024-03-28 19:03 UTC, closed without merging