Initial vagrant commit
intel-ai/icl pull request #9
Opened 2023-11-01 22:43 UTC by leshikus

Subj

2023-11-02 02:43 UTC, pbchekin approved these changes
Looks good for the first commit, commented a couple of nits.
Before merging please make sure the workflow is triggered manually and by cron, no need to run it for PRs and commits to main.

2023-11-02 02:43 UTC, pbchekin commented on .github/workflows/deploy-vagrant.yaml
> +name: Single node x1 with vagrant, Ubuntu, kind
It's not single node
```suggestion
name: Multi node cluster with Vagrant, Ubuntu, Kubespray
```

2023-11-02 02:43 UTC, pbchekin commented on scripts/ci/init.sh
> +    export X1_VAGRANT_DIR="$WORKSPACE_DIR"/"$X1_PREFIX"
Nit: this looks simpler:
```suggestion
    export X1_VAGRANT_DIR="$WORKSPACE_DIR/$X1_PREFIX"
```

2023-11-02 02:43 UTC, pbchekin commented on scripts/ci/init.sh
> +    WORKSPACE_DIR=$(dirname "$0")/../..
Nit: safer
```suggestion
    WORKSPACE_DIR="$(dirname "$0")/../.."
```

2023-11-06 12:17 UTC, leshikus commented on .github/workflows/deploy-vagrant.yaml
> +name: Single node x1 with vagrant, Ubuntu, kind
fixed

2023-11-06 12:17 UTC, leshikus commented on scripts/ci/init.sh
> +    export X1_VAGRANT_DIR="$WORKSPACE_DIR"/"$X1_PREFIX"
Fixed

2023-11-06 12:18 UTC, leshikus commented on scripts/ci/init.sh
> +    WORKSPACE_DIR=$(dirname "$0")/../..
Fixed

2023-11-06 12:59 UTC, leshikus commented on scripts/ci/init.sh
> +    WORKSPACE_DIR=$(dirname "$0")/../..
Reverted, the `$(` and `)` work like quotes. Here is a test:

```
mkdir a\ b
cat <<EOF >a\ b/test.sh
d=\$(dirname "\$0")/../..
echo \$d
EOF
cat a\ b/test.sh
sh a\ b/test.sh
```

2023-11-06 16:27 UTC, pbchekin requested changes
Please use the existing ansible/role/jumphost instead of ansible/role/configure-jumphost.

2023-11-06 21:22 UTC, leshikus commented
> Please use the existing ansible/role/jumphost instead of ansible/role/configure-jumphost.

fixed

2023-11-06 21:33 UTC, pbchekin approved these changes

2023-11-06 21:34 UTC, merged